apiVersion: v1
kind: Namespace
metadata:
  name: ldap
---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
